language: go

services:
  - docker

go:
  - 1.14.x

jobs:
  include:
    - stage: test
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.26.0
        - ./bin/golangci-lint run --timeout 5m
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: publish
      install: skip
      script:
        - docker build -t planetlabs/kostanza:${TRAVIS_COMMIT:0:7} .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push planetlabs/kostanza:${TRAVIS_COMMIT:0:7}

stages:
  - name: test
  - name: publish
    if: branch = master and not type = pull_request
